# Generated by Django 4.0 on 2022-01-03 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('is_complete', models.BooleanField(default=False, help_text='The completion status of the task.')),
                ('due_date', models.DateField(blank=True, help_text='Date task is scheduled to be completed.', null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, help_text='Date task was last modified.')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Date task was created.')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
